database:
  uri: ""
  track_modifications: false

flask:
  secret_key: 'ECE4150-Lab4'
  port: 5002

profile-service:
  url: "localhost:5004"

auth-service:
  url: "localhost:5001"

chatroom-service:
  url: "localhost:5003"